### ISSUE TITLE
jarring

### ISSUE THREAD

**Issue by malhal** [thoughtbot/TBAnnotationClustering#1]
very jarring to use when zooming in because the bubbles can appear out of no where. E.g. you are looking at a bubble, zoom in, then it disappears and other appear in different places. I think the clustering really needs to animate like Apple does in photo locations.

**Comment by hyperspacemark** [comment]
Hi Malcolm,

This repository serves mainly to accompany the content of the blog post (http://robots.thoughtbot.com/how-to-handle-large-amounts-of-data-on-maps/). While this example is production-ready, it was never intended to be a full-fledged clustering library; instead more of a tech demo.

As always, patches with new functionality are welcome.
