### ISSUE TITLE
Getting clustered annotation

### ISSUE THREAD

**Issue by Janak-Nirmal** [thoughtbot/TBAnnotationClustering#2]
Hi,

Thank you for this control.

Is it possible to get all clustered annotation when we click on any annotation ? e.g. we can get count of the a clustered annotation but which places where covered under that clustered pin is what I am looking for, was not able to find it so just a quick question.

Thanks,

**Comment by theocalmes** [comment]
Yes.

under - `(NSArray *)clusteredAnnotationsWithinMapRect:(MKMapRect)rect withZoomScale:(double)zoomScale`

```
TBQuadTreeGatherDataInRange(self.root, TBBoundingBoxForMapRect(mapRect), ^(TBQuadTreeNodeData data) {
                totalX += data.x;
                totalY += data.y;
                count++;

                TBHotelInfo hotelInfo = *(TBHotelInfo *)data.data;
                [names addObject:[NSString stringWithFormat:@"%s", hotelInfo.hotelName]];
                [phoneNumbers addObject:[NSString stringWithFormat:@"%s", hotelInfo.hotelPhoneNumber]];
            });
```

gives you everything within a cluster. You could modify this function to keep refs to all the data in your annotation.
